{% macro create_apt_data_tables(db_name, schema_name) %}
DROP TABLE
  IF EXISTS {{ db_name }}.{{ schema_name }}.APT_DATA CASCADE;


CREATE TABLE
  IF NOT EXISTS {{ db_name }}.{{ schema_name }}.APT_DATA (
    ID SERIAL PRIMARY KEY,
    APT_ID INTEGER,
    SHORT_DESCRIPTION TEXT,
    TITLE TEXT,
    DESCRIPTION TEXT,
    UNIT_TYPES TEXT,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    LINK TEXT,
    STATUS TEXT,
    IMAGES TEXT [] [],
    ADDRESS_COUNTRY TEXT,
    ADDRESS_CITY TEXT,
    ADDRESS_ZONE TEXT,
    ADDRESS_DISTRICT TEXT,
    ADDRESS_NEIGHBORHOOD TEXT,
    ADDRESS_STREET TEXT,
    ADDRESS_STREET_NUMBER INTEGER,
    ADDRESS_ZIP_CODE INTEGER,
    ADDRESS_LEVEL TEXT,
    ADDRESS_LONGITUDE DOUBLE PRECISION,
    ADDRESS_LATITUDE DOUBLE PRECISION,
    PRICING_BUSINESS_TYPE TEXT,
    PRICING_PERIOD TEXT,
    PRICING_RENT DOUBLE PRECISION,
    PRICING_MONTHLY_CONDO_FEE DOUBLE PRECISION,
    PRICING_YEARLY_IPTU DOUBLE PRECISION,
    PRICING_MONTHLY_TOTAL DOUBLE PRECISION,
    TOTAL_AREA_M2 DOUBLE PRECISION,
    NUM_BEDROOMS INTEGER,
    NUM_BATHROOMS INTEGER,
    PARKING_SPACES INTEGER,
    FLOORS INTEGER,
    UNIT_FLOOR INTEGER,
    LISTING_TYPE TEXT,
    AMENITIES TEXT [],
    POINTS_OF_INTEREST TEXT [],
    FULL_LINK TEXT
  );


{% endmacro %}