name: Dev

on:
    push:
        branches:
            - dev
            - story**
            - feature**
            - bug**
            - chore**
            - hotfix**

jobs:
    dev:
        uses: ./.github/workflows/deploy-stack.yml
        with:
            stage: dev
        secrets: inherit
