name: Release

on:
    push:
        branches:
            - release**

jobs:
    release:
        uses: ./.github/workflows/deploy-stack.yml
        with:
            stage: release
        secrets: inherit
